### ISSUE TITLE
Mel_filters problem and information.

### ISSUE THREAD

**Issue by MoonDragon-MD** [ssciwr/vink#44]
Hi, I wanted to try the program but if I try to put a wav or mp4, either with CPU or GPU, I get the following error: 

```
Traceback (most recent call last):
  File "vink.py", line 221, in transcribe
  File "whisper\transcribe.py", line 122, in transcribe
  File "whisper\audio.py", line 151, in log_mel_spectrogram
  File "whisper\audio.py", line 106, in mel_filters
  File "numpy\lib\npyio.py", line 427, in load
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\Vink\\_internal\\whisper\\assets\\mel_filters.npz'
```

The file would be this [mel_filters.npz](https://github.com/openai/whisper/blob/main/whisper/assets/mel_filters.npz) , but in what folder should it be put?

Also I would like to know what folder it saves the model in when it downloads them? (I have other programs with whisper I would like to use the models I already have without saturating the space)

**Comment by MatteoPrampolini** [comment]
I encountered the same issue and was able to resolve it by downloading the 3 files from [this directory](https://github.com/openai/whisper/tree/main/whisper/assets) and placing them in the folder specified in the `FileNotFoundError: [Errno 2] No such file or directory` message.

**Comment by MoonDragon-MD** [comment]
@MatteoPrampolini Perfect works!
